### PR TITLE
Fix tracker detail fragment layout

### LINKED ISSUE #191: App give focus on wrong fragment
### Issues: 
* Device: Honor 8
* OS: Android 8

How reproduce:
* 1 :
  * Start app
  * Go to trackers tab
  * Consult tracker -> Focus is gived to [recycler_view_app_item](https://github.com/Exodus-Privacy/exodus-android-app/blob/kotlinRewrite/app/src/main/res/layout/recycler_view_app_item.xml)
* 2 : 
    * Start app
    * Consult report
    * Open report on Exodus with this button [openExodusPage ](https://github.com/Exodus-Privacy/exodus-android-app/blob/aadb28a06efb2d81d8290710b999a390cb43211e/app/src/main/res/menu/app_detail_menu.xml#L5)
    * Go back to app -> Focus is gived to [fragment_a_d_trackers](https://github.com/Exodus-Privacy/exodus-android-app/blob/kotlinRewrite/app/src/main/res/layout/fragment_a_d_trackers.xml)

Maybe this issue is specific on device with a little screen ?

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
This PR fixes:
- Scrolling not working properly -> introduced by #398
- Fix number of apps present in the list -> introduced by #309 (In latest version, we can see at the maximum, 8 apps in list)

Before

https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/42f29c01-7f9a-469a-bfda-f047caf4e7ad

After

https://github.com/Exodus-Privacy/exodus-android-app/assets/87148630/39520b11-cf0a-463f-9a54-4b5833a5dc72

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
@connyduck did you have a better option?

**Comment by connyduck** [comment]
I think the right fix is to move the `RecyclerView` out of the `AppBarLayout` and make it a direct child of the `CoordinatorLayout`, then add the correct `layout_behavior` and make the height `match_parent`. Like this: 

```
<androidx.coordinatorlayout.widget.CoordinatorLayout ... >

    <com.google.android.material.appbar.AppBarLayout ... >
        ...
    </com.google.android.material.appbar.AppBarLayout>

    <androidx.recyclerview.widget.RecyclerView
        android:id="@+id/appsListRV"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="5dp"
        android:visibility="gone"
        app:layout_behavior="com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

And in the FragmentCode allow vertical scrolling:

```diff
-layoutManager = object : StaggeredGridLayoutManager(column, 1) {
-    override fun canScrollVertically(): Boolean {
-        return false
-    }
-}
+layoutManager = StaggeredGridLayoutManager(column, 1)
```

Pretty much the same as the `AppDetailFragment` is set up now. I can send a PR if you want.

File: app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackerdetail/TrackerDetailFragment.kt [hunk 1]
```diff
@@ -150,11 +150,7 @@ class TrackerDetailFragment : Fragment(R.layout.fragment_tracker_detail) {
                         } else {
                             1
                         }
-                    layoutManager = object : StaggeredGridLayoutManager(column, 1) {
-                        override fun canScrollVertically(): Boolean {
-                            return false
-                        }
-                    }
+                    layoutManager = object : StaggeredGridLayoutManager(column, 1) {}
```
Comment (connyduck) [inline app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackerdetail/TrackerDetailFragment.kt:153]:
```suggestion
                    layoutManager = StaggeredGridLayoutManager(column, 1)
```

**Review by connyduck — APPROVED** [review]

**Review by codeurimpulsif — APPROVED** [review]
